# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'labeling_tool_main.ui'
##
## Created by: Qt User Interface Compiler version 6.4.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QGroupBox, QLabel, QLineEdit,
    QListWidget, QListWidgetItem, QMainWindow, QMenu,
    QMenuBar, QProgressBar, QPushButton, QSizePolicy,
    QStatusBar, QTabWidget, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1026, 699)
        MainWindow.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.actionOpen_Workspace = QAction(MainWindow)
        self.actionOpen_Workspace.setObjectName(u"actionOpen_Workspace")
        self.actionCreate_New_Database = QAction(MainWindow)
        self.actionCreate_New_Database.setObjectName(u"actionCreate_New_Database")
        self.actionBlob_Detector_With_Face_Parsing = QAction(MainWindow)
        self.actionBlob_Detector_With_Face_Parsing.setObjectName(u"actionBlob_Detector_With_Face_Parsing")
        self.actionParse_Current_Image = QAction(MainWindow)
        self.actionParse_Current_Image.setObjectName(u"actionParse_Current_Image")
        self.actionUpdate_Database = QAction(MainWindow)
        self.actionUpdate_Database.setObjectName(u"actionUpdate_Database")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.imageTab = QTabWidget(self.centralwidget)
        self.imageTab.setObjectName(u"imageTab")
        self.imageTab.setGeometry(QRect(0, 40, 710, 540))
        self.imageTab.setUsesScrollButtons(False)
        self.imageTab.setTabBarAutoHide(True)
        self.imageRawTab = QWidget()
        self.imageRawTab.setObjectName(u"imageRawTab")
        self.imageLabelTabRaw = QLabel(self.imageRawTab)
        self.imageLabelTabRaw.setObjectName(u"imageLabelTabRaw")
        self.imageLabelTabRaw.setGeometry(QRect(0, 0, 706, 509))
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageLabelTabRaw.sizePolicy().hasHeightForWidth())
        self.imageLabelTabRaw.setSizePolicy(sizePolicy)
        self.imageLabelTabRaw.setAutoFillBackground(True)
        self.imageLabelTabRaw.setScaledContents(False)
        self.imageTab.addTab(self.imageRawTab, "")
        self.imageSegTab = QWidget()
        self.imageSegTab.setObjectName(u"imageSegTab")
        self.imageLabelTabSeg = QLabel(self.imageSegTab)
        self.imageLabelTabSeg.setObjectName(u"imageLabelTabSeg")
        self.imageLabelTabSeg.setGeometry(QRect(0, 0, 706, 509))
        sizePolicy.setHeightForWidth(self.imageLabelTabSeg.sizePolicy().hasHeightForWidth())
        self.imageLabelTabSeg.setSizePolicy(sizePolicy)
        self.imageLabelTabSeg.setAutoFillBackground(True)
        self.imageLabelTabSeg.setScaledContents(False)
        self.imageTab.addTab(self.imageSegTab, "")
        self.imageBlobTab = QWidget()
        self.imageBlobTab.setObjectName(u"imageBlobTab")
        self.imageLabelTabBlob = QLabel(self.imageBlobTab)
        self.imageLabelTabBlob.setObjectName(u"imageLabelTabBlob")
        self.imageLabelTabBlob.setGeometry(QRect(0, 0, 706, 509))
        sizePolicy.setHeightForWidth(self.imageLabelTabBlob.sizePolicy().hasHeightForWidth())
        self.imageLabelTabBlob.setSizePolicy(sizePolicy)
        self.imageLabelTabBlob.setAutoFillBackground(True)
        self.imageLabelTabBlob.setScaledContents(False)
        self.imageTab.addTab(self.imageBlobTab, "")
        self.rightUpperGroupBox = QGroupBox(self.centralwidget)
        self.rightUpperGroupBox.setObjectName(u"rightUpperGroupBox")
        self.rightUpperGroupBox.setGeometry(QRect(760, 0, 261, 331))
        self.rightUpperGroupBox.setMinimumSize(QSize(0, 321))
        self.rightUpperGroupBox.setContextMenuPolicy(Qt.NoContextMenu)
        self.rightUpperGroupBox.setLayoutDirection(Qt.LeftToRight)
        self.rightUpperGroupBox.setAutoFillBackground(False)
        self.rightUpperGroupBox.setStyleSheet(u"")
        self.rightUpperGroupBox.setAlignment(Qt.AlignCenter)
        self.rightUpperGroupBox.setFlat(True)
        self.labelList = QListWidget(self.rightUpperGroupBox)
        self.labelList.setObjectName(u"labelList")
        self.labelList.setGeometry(QRect(20, 180, 221, 121))
        self.labelListTitle = QLabel(self.rightUpperGroupBox)
        self.labelListTitle.setObjectName(u"labelListTitle")
        self.labelListTitle.setGeometry(QRect(20, 160, 91, 16))
        self.labelListTitle.setScaledContents(True)
        self.addLabelButton = QPushButton(self.rightUpperGroupBox)
        self.addLabelButton.setObjectName(u"addLabelButton")
        self.addLabelButton.setGeometry(QRect(20, 90, 151, 21))
        self.keyBindEdit = QLineEdit(self.rightUpperGroupBox)
        self.keyBindEdit.setObjectName(u"keyBindEdit")
        self.keyBindEdit.setGeometry(QRect(110, 60, 121, 20))
        self.keyBindTitle = QLabel(self.rightUpperGroupBox)
        self.keyBindTitle.setObjectName(u"keyBindTitle")
        self.keyBindTitle.setGeometry(QRect(20, 60, 71, 16))
        self.keyBindTitle.setScaledContents(True)
        self.labelNameEdit = QLineEdit(self.rightUpperGroupBox)
        self.labelNameEdit.setObjectName(u"labelNameEdit")
        self.labelNameEdit.setGeometry(QRect(110, 30, 121, 20))
        self.labelNameTitle = QLabel(self.rightUpperGroupBox)
        self.labelNameTitle.setObjectName(u"labelNameTitle")
        self.labelNameTitle.setGeometry(QRect(20, 30, 91, 16))
        self.labelNameTitle.setScaledContents(True)
        self.removeLabelButton = QPushButton(self.rightUpperGroupBox)
        self.removeLabelButton.setObjectName(u"removeLabelButton")
        self.removeLabelButton.setGeometry(QRect(20, 120, 151, 21))
        self.upperGroupBox = QGroupBox(self.centralwidget)
        self.upperGroupBox.setObjectName(u"upperGroupBox")
        self.upperGroupBox.setGeometry(QRect(0, 10, 710, 30))
        self.dbStatus = QLabel(self.upperGroupBox)
        self.dbStatus.setObjectName(u"dbStatus")
        self.dbStatus.setGeometry(QRect(480, 0, 221, 30))
        self.dbStatus.setScaledContents(True)
        self.dbStatus.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.imageIDCount = QLabel(self.upperGroupBox)
        self.imageIDCount.setObjectName(u"imageIDCount")
        self.imageIDCount.setGeometry(QRect(10, 0, 341, 30))
        self.imageIDCount.setScaledContents(True)
        self.rightBelowGroupBox = QGroupBox(self.centralwidget)
        self.rightBelowGroupBox.setObjectName(u"rightBelowGroupBox")
        self.rightBelowGroupBox.setGeometry(QRect(760, 330, 261, 255))
        self.curImageLabelTitle = QLabel(self.rightBelowGroupBox)
        self.curImageLabelTitle.setObjectName(u"curImageLabelTitle")
        self.curImageLabelTitle.setGeometry(QRect(20, 10, 171, 16))
        self.curImageLabelTitle.setScaledContents(True)
        self.curImageLabelsList = QListWidget(self.rightBelowGroupBox)
        self.curImageLabelsList.setObjectName(u"curImageLabelsList")
        self.curImageLabelsList.setGeometry(QRect(20, 40, 221, 121))
        self.prevImageButton = QPushButton(self.rightBelowGroupBox)
        self.prevImageButton.setObjectName(u"prevImageButton")
        self.prevImageButton.setGeometry(QRect(20, 214, 91, 31))
        self.nextImageButton = QPushButton(self.rightBelowGroupBox)
        self.nextImageButton.setObjectName(u"nextImageButton")
        self.nextImageButton.setGeometry(QRect(150, 214, 91, 31))
        self.focusModeButton = QPushButton(self.rightBelowGroupBox)
        self.focusModeButton.setObjectName(u"focusModeButton")
        self.focusModeButton.setGeometry(QRect(20, 170, 91, 31))
        self.focusStatus = QLabel(self.rightBelowGroupBox)
        self.focusStatus.setObjectName(u"focusStatus")
        self.focusStatus.setGeometry(QRect(150, 170, 81, 31))
        self.focusStatus.setScaledContents(True)
        self.bottomGroupBox = QGroupBox(self.centralwidget)
        self.bottomGroupBox.setObjectName(u"bottomGroupBox")
        self.bottomGroupBox.setGeometry(QRect(0, 590, 1021, 51))
        self.bottomGroupBox.setAutoFillBackground(True)
        self.bottomProgressBar = QProgressBar(self.bottomGroupBox)
        self.bottomProgressBar.setObjectName(u"bottomProgressBar")
        self.bottomProgressBar.setGeometry(QRect(13, 13, 95, 25))
        self.bottomProgressBar.setValue(24)
        self.progressBarText = QLabel(self.bottomGroupBox)
        self.progressBarText.setObjectName(u"progressBarText")
        self.progressBarText.setGeometry(QRect(140, 13, 311, 25))
        self.progressBarText.setScaledContents(True)
        self.progressBarText.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1026, 22))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuDatabase = QMenu(self.menubar)
        self.menuDatabase.setObjectName(u"menuDatabase")
        self.menuTools = QMenu(self.menubar)
        self.menuTools.setObjectName(u"menuTools")
        self.menuBlob_Detector = QMenu(self.menuTools)
        self.menuBlob_Detector.setObjectName(u"menuBlob_Detector")
        self.menuFace_Parsing_Tool = QMenu(self.menuTools)
        self.menuFace_Parsing_Tool.setObjectName(u"menuFace_Parsing_Tool")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        self.statusbar.setSizeGripEnabled(False)
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuDatabase.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menuFile.addAction(self.actionOpen_Workspace)
        self.menuDatabase.addAction(self.actionCreate_New_Database)
        self.menuDatabase.addAction(self.actionUpdate_Database)
        self.menuTools.addAction(self.menuFace_Parsing_Tool.menuAction())
        self.menuTools.addAction(self.menuBlob_Detector.menuAction())
        self.menuBlob_Detector.addAction(self.actionBlob_Detector_With_Face_Parsing)
        self.menuFace_Parsing_Tool.addAction(self.actionParse_Current_Image)

        self.retranslateUi(MainWindow)

        self.imageTab.setCurrentIndex(2)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Labeling Tool", None))
        self.actionOpen_Workspace.setText(QCoreApplication.translate("MainWindow", u"Open Workspace", None))
        self.actionCreate_New_Database.setText(QCoreApplication.translate("MainWindow", u"Create New Database", None))
        self.actionBlob_Detector_With_Face_Parsing.setText(QCoreApplication.translate("MainWindow", u"Blob Detector With Face Parsing", None))
        self.actionParse_Current_Image.setText(QCoreApplication.translate("MainWindow", u"Parse Current Image", None))
        self.actionUpdate_Database.setText(QCoreApplication.translate("MainWindow", u"Update Database", None))
        self.imageLabelTabRaw.setText("")
        self.imageTab.setTabText(self.imageTab.indexOf(self.imageRawTab), QCoreApplication.translate("MainWindow", u"Raw", None))
        self.imageLabelTabSeg.setText("")
        self.imageTab.setTabText(self.imageTab.indexOf(self.imageSegTab), QCoreApplication.translate("MainWindow", u"Seg", None))
        self.imageLabelTabBlob.setText("")
        self.imageTab.setTabText(self.imageTab.indexOf(self.imageBlobTab), QCoreApplication.translate("MainWindow", u"blob", None))
        self.rightUpperGroupBox.setTitle("")
        self.labelListTitle.setText(QCoreApplication.translate("MainWindow", u"Label List:", None))
        self.addLabelButton.setText(QCoreApplication.translate("MainWindow", u"Add Label", None))
        self.keyBindTitle.setText(QCoreApplication.translate("MainWindow", u"Keybind:", None))
        self.labelNameTitle.setText(QCoreApplication.translate("MainWindow", u"Label Name:", None))
        self.removeLabelButton.setText(QCoreApplication.translate("MainWindow", u"Remove Label", None))
        self.upperGroupBox.setTitle("")
        self.dbStatus.setText(QCoreApplication.translate("MainWindow", u"dbStatus", None))
        self.imageIDCount.setText(QCoreApplication.translate("MainWindow", u"image_id", None))
        self.rightBelowGroupBox.setTitle("")
        self.curImageLabelTitle.setText(QCoreApplication.translate("MainWindow", u"Current Image Labels:", None))
        self.prevImageButton.setText(QCoreApplication.translate("MainWindow", u"Prev", None))
        self.nextImageButton.setText(QCoreApplication.translate("MainWindow", u"Next", None))
        self.focusModeButton.setText(QCoreApplication.translate("MainWindow", u"Focus Mode", None))
        self.focusStatus.setText(QCoreApplication.translate("MainWindow", u"OFF", None))
        self.bottomGroupBox.setTitle("")
        self.progressBarText.setText(QCoreApplication.translate("MainWindow", u"progressbartext", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuDatabase.setTitle(QCoreApplication.translate("MainWindow", u"Database", None))
        self.menuTools.setTitle(QCoreApplication.translate("MainWindow", u"Tools", None))
        self.menuBlob_Detector.setTitle(QCoreApplication.translate("MainWindow", u"Blob Detector", None))
        self.menuFace_Parsing_Tool.setTitle(QCoreApplication.translate("MainWindow", u"Face Parsing Tool", None))
    # retranslateUi

